# Generated by Django 4.0.5 on 2022-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='media')),
                ('rasm1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('rasm2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('malumot', models.CharField(max_length=200)),
            ],
        ),
    ]
