# Generated by Django 4.0.5 on 2022-12-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='malumot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.malumot'),
        ),
    ]
