# Generated by Django 4.0.5 on 2022-12-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_lavozim_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('vaqt', models.DateField()),
            ],
        ),
    ]
