# Generated by Django 4.0.5 on 2023-01-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_gmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gmail',
        ),
    ]
